# Generated by Django 4.2.21 on 2025-11-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('idNumber', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('publicity', models.CharField(choices=[('', 'Valitse tilan julkisuus'), ('private', 'Yksityinen'), ('public', 'Julkinen')], default='', max_length=20)),
                ('service_type', models.CharField(choices=[('', 'Valitse tilan palvelutyyppi'), ('rental', 'Vuokra'), ('loan', 'Laina')], default='', max_length=20)),
                ('type', models.CharField(choices=[('', 'Valitse tilan tyyppi'), ('office', 'Toimisto'), ('meeting_room', 'Kokoushuone'), ('conference_room', 'Konferenssihuone'), ('event_space', 'Tapahtumatila')], default='', max_length=20)),
                ('size', models.CharField(blank=True, default='0', max_length=10, verbose_name='Size m²')),
                ('capacity', models.CharField(blank=True, default='0', max_length=10, verbose_name='Capacity')),
                ('slug', models.SlugField(default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.space')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start', 'id'],
            },
        ),
    ]
