# Generated by Django 4.2.21 on 2025-11-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='user',
        ),
    ]
