# Generated by Django 4.2.21 on 2025-11-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='space',
            name='municipality',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
