# Generated by Django 4.2.21 on 2025-11-02 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_remove_space_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
