# Generated by Django 4.2.21 on 2025-08-20 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.space'),
        ),
    ]
