# Generated by Django 4.2.21 on 2025-08-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_event_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='space',
        ),
    ]
