# Generated by Django 4.2.21 on 2025-11-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_space_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reserver_email',
            field=models.EmailField(blank=True, help_text='Varaajan sähköpostiosoite (kirjautunut tai manuaalisesti annettu)', max_length=254, null=True, verbose_name='sähköposti'),
        ),
    ]
