# Generated by Django 4.2.21 on 2025-08-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_event_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.space'),
            preserve_default=False,
        ),
    ]
