# Generated by Django 4.2.21 on 2025-09-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='idNumber',
        ),
    ]
