# Generated by Django 4.2.21 on 2025-09-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_id_user_idnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='reservation',
        ),
    ]
