# Generated by Django 4.2.21 on 2025-10-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_delete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start', 'id']},
        ),
    ]
