# Generated by Django 4.2.21 on 2025-10-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reserver_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reserver_firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='reserver_lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
